language: csharp
mono: latest
dotnet: 3.1
script:
  - dotnet restore
  - nuget install docfx.console  -Version $DOCFX_VERSION
  - ls
  - ls docfx.console.$DOCFX_VERSION
  - mono ./docfx.console.$DOCFX_VERSION/tools/docfx.exe build docfx_project/docfx.json
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docfx_project/_site
  on:
    branch: 
      - master
      - develop
      - feature/docfx