language: csharp
mono: latest
dotnet: 3.1
script:
  - dotnet restore
  - nuget install docfx.console  -Version $DOCFX_VERSION
  - ls
  - ls docfx.console.$DOCFX_VERSION
  - mono ./docfx.console.$DOCFX_VERSION/tools/docfx.exe build docfx_project/docfx.json
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docfx_project/_site
#  on:
#    branch: master
#jobs:
#  include:
#    - stage: "Build"
#    - script:
#      - dotnet restore
#      - dotnet build
#    - stage: "Test"
#    - script:
#      - dotnet restore
#      - dotnet test tests/GravyIrc.Tests/GravyIrc.Tests.csproj
#    - stage: "Docs"
#    - script:
#      - nuget install docfx.console
