name: CI

on:
  push:
    paths-ignore: ['**.md', 'art/**', 'docs/**', '.vscode/**']
    branches:
    - master
  pull_request:
    paths-ignore: ['**.md', 'art/**', 'docs/**', '.vscode/**']
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh
    - name: Publish coverage report to coveralls.io
      if: matrix.os == 'ubuntu-latest'
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: tests/NetIRC.Tests/TestResults/coverage.info
    - name: Push to MyGet
      if: matrix.os == 'ubuntu-latest'
      run: dotnet nuget push artifacts/*.nupkg -s https://www.myget.org/F/netirc/api/v3/index.json -k ${{ secrets.MYGET_TOKEN }}
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts/*
